### ISSUE TITLE
[Feature]: quantum utils docstrings and tests

### ISSUE THREAD

**Issue by aarontrowbridge** [aarontrowbridge/QuantumCollocation.jl#102]
### Feature Description

We are looking for someone to write docstrings and tests for all of the functions in the file [src/quantum_utils.jl](https://github.com/aarontrowbridge/QuantumCollocation.jl/blob/main/src/quantum_utils.jl).

Some docstrings are in place, but a lot are not. The extant ones, if necessary, should be expanded to include a description of the function and the arguments, in line with the [blue style guidelines](https://github.com/JuliaDiff/BlueStyle?tab=readme-ov-file#documentation).

#### Implementation details

- Write docstrings for all of the functions in `src/quantum_utils.jl`
- Add tests for the functions in [`test/quantum_utils_test.jl`](https://github.com/aarontrowbridge/QuantumCollocation.jl/blob/main/test/quantum_utils_test.jl)
 

### Importance

1 (lowest)

### What does this feature affect?

- [ ] quantum system construction
- [ ] problem setup
- [ ] problem solution
- [ ] problem performance
- [ ] solution analysis
- [ ] plotting
- [X] documentation
- [X] tests
- [ ] other (please specify below)

**Comment by Fe-r-oz** [comment]
Sounds interesting! I would like to work on this.

**Comment by andgoldschmidt** [comment]
@Fe-r-oz It's yours to pursue! Check the [contribution guide](https://aarontrowbridge.github.io/QuantumCollocation.jl/dev/contribution_guide/) for some notes regarding testing. 

Feedback on the naming and interpretability of the utilities is appreciated at this time. We also welcome suggestions for missing utilities, filling gaps or improving what has currently been made available.

**Comment by Fe-r-oz** [comment]
Hi, @aarontrowbridge, Kindly please review the PR https://github.com/aarontrowbridge/QuantumCollocation.jl/pull/111. All the tests passed passed. 

Since it has both documentation and testing, it's a little long.  But I followed the best practices from the guide [See also, this guide.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests).  If there is something wrong, please let me know in the review. 

I also included comments to better expain each and every test. I hope the PR satisfies the requirements. Thank you.

**Comment by Fe-r-oz** [comment]
Hi, Please close this issue as it's resolved! Thanks!
